spring:
    application:
      name: news-db-back-end
    datasource:
      username: postgres
      url: jdbc:postgresql://localhost:5432/news
      driverClassName: org.postgresql.Driver
      password: 'mysecretpassword'
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      show-sql: 'true'


  server:
    port: 8017



  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/